### ISSUE TITLE
Purchase validation failed

### ISSUE THREAD

**Issue by sailor002** [Teknasyon-Teknoloji/deepwall-ios-sdk#2]
Hi,

After the purchase is successfully completed, it gives an error message saying "Purchase validation failed" and "deepWallPaywallPurchaseFailed" observer method is fired. When I make the same purchase with my own standard in-app purchase helper class, there is no problem. Any ideas?

**Comment by buraksyalcin** [comment]
There was a temporary problem in the product validation service, I guess you came across this.
Are you still getting the same error?

**Comment by sailor002** [comment]
Unfortunately, still getting the same error.

**Comment by buraksyalcin** [comment]
Can you share your environment details for purchases? (Xcode, sandbox or production)

**Comment by sailor002** [comment]
The purchasing environment is Xcode Storekit.

**Comment by buraksyalcin** [comment]
Unfortunately validating Xcode StoreKit receipts by Apple server-side are not possible at the moment because of Apple. You can use sandbox environment for testing purposes.

**Comment by sailor002** [comment]
Thanks for the information. As you say, the issue seems to be related to Xcode StoreKit testing.
